CREATE TABLE public.whatsapp_campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  inbox_id uuid NOT NULL REFERENCES public.inboxes(id) ON DELETE RESTRICT,
  persona_id uuid NOT NULL REFERENCES public.agent_personas(id) ON DELETE RESTRICT,
  name text NOT NULL,
  audience_mode text NOT NULL DEFAULT 'selected' CHECK (audience_mode IN ('selected', 'all_open')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'running', 'paused', 'completed', 'failed', 'canceled')),
  scheduled_for timestamptz,
  daily_limit integer NOT NULL DEFAULT 100 CHECK (daily_limit BETWEEN 1 AND 1000),
  contact_count integer NOT NULL DEFAULT 0,
  sent_count integer NOT NULL DEFAULT 0,
  replied_count integer NOT NULL DEFAULT 0,
  skipped_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  created_by_id uuid,
  started_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.whatsapp_campaigns TO authenticated;
GRANT ALL ON public.whatsapp_campaigns TO service_role;
ALTER TABLE public.whatsapp_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Account members can view WhatsApp campaigns"
ON public.whatsapp_campaigns FOR SELECT TO authenticated
USING (public.is_account_member(auth.uid(), account_id));

CREATE TABLE public.whatsapp_campaign_recipients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id uuid NOT NULL REFERENCES public.whatsapp_campaigns(id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  contact_id uuid NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  debt_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
  phone_number text NOT NULL,
  debt_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  generated_message text,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'generating', 'sending', 'sent', 'replied', 'skipped', 'failed')),
  dispatch_after timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  replied_at timestamptz,
  conversation_id uuid REFERENCES public.conversations(id) ON DELETE SET NULL,
  message_id uuid REFERENCES public.messages(id) ON DELETE SET NULL,
  provider_message_id text,
  skip_reason text,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campaign_id, contact_id)
);
GRANT SELECT ON public.whatsapp_campaign_recipients TO authenticated;
GRANT ALL ON public.whatsapp_campaign_recipients TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.whatsapp_campaign_recipients_id_seq TO authenticated, service_role;
ALTER TABLE public.whatsapp_campaign_recipients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Account members can view WhatsApp campaign recipients"
ON public.whatsapp_campaign_recipients FOR SELECT TO authenticated
USING (public.is_account_member(auth.uid(), account_id));

CREATE INDEX whatsapp_campaigns_account_created_idx ON public.whatsapp_campaigns(account_id, created_at DESC);
CREATE INDEX whatsapp_campaigns_dispatch_idx ON public.whatsapp_campaigns(status, scheduled_for);
CREATE INDEX whatsapp_campaign_recipients_dispatch_idx ON public.whatsapp_campaign_recipients(status, dispatch_after);
CREATE INDEX whatsapp_campaign_recipients_campaign_status_idx ON public.whatsapp_campaign_recipients(campaign_id, status);
CREATE INDEX whatsapp_campaign_recipients_conversation_idx ON public.whatsapp_campaign_recipients(conversation_id) WHERE conversation_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.mark_whatsapp_campaign_reply()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.sender_type = 'Contact' THEN
    UPDATE public.whatsapp_campaign_recipients
       SET status = 'replied', replied_at = COALESCE(replied_at, NEW.created_at), updated_at = now()
     WHERE conversation_id = NEW.conversation_id
       AND status = 'sent';

    UPDATE public.whatsapp_campaigns c
       SET replied_count = (
         SELECT count(*) FROM public.whatsapp_campaign_recipients r
          WHERE r.campaign_id = c.id AND r.status = 'replied'
       ), updated_at = now()
     WHERE EXISTS (
       SELECT 1 FROM public.whatsapp_campaign_recipients r
        WHERE r.campaign_id = c.id AND r.conversation_id = NEW.conversation_id
     );
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.mark_whatsapp_campaign_reply() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.mark_whatsapp_campaign_reply() TO service_role;
CREATE TRIGGER mark_whatsapp_campaign_reply_after_message
AFTER INSERT ON public.messages
FOR EACH ROW EXECUTE FUNCTION public.mark_whatsapp_campaign_reply();