/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVoiceCampaignsRouteImport } from './routes/_authenticated/voice-campaigns'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecuperacaoRouteImport } from './routes/_authenticated/recuperacao'
import { Route as AuthenticatedPhoneNumbersRouteImport } from './routes/_authenticated/phone-numbers'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAcordosRouteImport } from './routes/_authenticated/acordos'
import { Route as ApiPublicTwilioBiaDialRouteImport } from './routes/api/public/twilio/bia-dial'
import { Route as ApiPublicHooksVoiceCallsFinalizePendingRouteImport } from './routes/api/public/hooks/voice-calls-finalize-pending'
import { Route as ApiPublicHooksDebtorsAutoSyncRouteImport } from './routes/api/public/hooks/debtors-auto-sync'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVoiceCampaignsRoute =
  AuthenticatedVoiceCampaignsRouteImport.update({
    id: '/voice-campaigns',
    path: '/voice-campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecuperacaoRoute =
  AuthenticatedRecuperacaoRouteImport.update({
    id: '/recuperacao',
    path: '/recuperacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPhoneNumbersRoute =
  AuthenticatedPhoneNumbersRouteImport.update({
    id: '/phone-numbers',
    path: '/phone-numbers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcordosRoute = AuthenticatedAcordosRouteImport.update({
  id: '/acordos',
  path: '/acordos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTwilioBiaDialRoute = ApiPublicTwilioBiaDialRouteImport.update({
  id: '/api/public/twilio/bia-dial',
  path: '/api/public/twilio/bia-dial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVoiceCallsFinalizePendingRoute =
  ApiPublicHooksVoiceCallsFinalizePendingRouteImport.update({
    id: '/api/public/hooks/voice-calls-finalize-pending',
    path: '/api/public/hooks/voice-calls-finalize-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDebtorsAutoSyncRoute =
  ApiPublicHooksDebtorsAutoSyncRouteImport.update({
    id: '/api/public/hooks/debtors-auto-sync',
    path: '/api/public/hooks/debtors-auto-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/acordos': typeof AuthenticatedAcordosRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/voice-campaigns': typeof AuthenticatedVoiceCampaignsRoute
  '/api/public/hooks/debtors-auto-sync': typeof ApiPublicHooksDebtorsAutoSyncRoute
  '/api/public/hooks/voice-calls-finalize-pending': typeof ApiPublicHooksVoiceCallsFinalizePendingRoute
  '/api/public/twilio/bia-dial': typeof ApiPublicTwilioBiaDialRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/acordos': typeof AuthenticatedAcordosRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/voice-campaigns': typeof AuthenticatedVoiceCampaignsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/debtors-auto-sync': typeof ApiPublicHooksDebtorsAutoSyncRoute
  '/api/public/hooks/voice-calls-finalize-pending': typeof ApiPublicHooksVoiceCallsFinalizePendingRoute
  '/api/public/twilio/bia-dial': typeof ApiPublicTwilioBiaDialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/acordos': typeof AuthenticatedAcordosRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/_authenticated/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/voice-campaigns': typeof AuthenticatedVoiceCampaignsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/debtors-auto-sync': typeof ApiPublicHooksDebtorsAutoSyncRoute
  '/api/public/hooks/voice-calls-finalize-pending': typeof ApiPublicHooksVoiceCallsFinalizePendingRoute
  '/api/public/twilio/bia-dial': typeof ApiPublicTwilioBiaDialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/acordos'
    | '/agents'
    | '/calls'
    | '/chat'
    | '/contacts'
    | '/equipe'
    | '/historico'
    | '/phone-numbers'
    | '/recuperacao'
    | '/settings'
    | '/voice-campaigns'
    | '/api/public/hooks/debtors-auto-sync'
    | '/api/public/hooks/voice-calls-finalize-pending'
    | '/api/public/twilio/bia-dial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/acordos'
    | '/agents'
    | '/calls'
    | '/chat'
    | '/contacts'
    | '/equipe'
    | '/historico'
    | '/phone-numbers'
    | '/recuperacao'
    | '/settings'
    | '/voice-campaigns'
    | '/'
    | '/api/public/hooks/debtors-auto-sync'
    | '/api/public/hooks/voice-calls-finalize-pending'
    | '/api/public/twilio/bia-dial'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/acordos'
    | '/_authenticated/agents'
    | '/_authenticated/calls'
    | '/_authenticated/chat'
    | '/_authenticated/contacts'
    | '/_authenticated/equipe'
    | '/_authenticated/historico'
    | '/_authenticated/phone-numbers'
    | '/_authenticated/recuperacao'
    | '/_authenticated/settings'
    | '/_authenticated/voice-campaigns'
    | '/_authenticated/'
    | '/api/public/hooks/debtors-auto-sync'
    | '/api/public/hooks/voice-calls-finalize-pending'
    | '/api/public/twilio/bia-dial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksDebtorsAutoSyncRoute: typeof ApiPublicHooksDebtorsAutoSyncRoute
  ApiPublicHooksVoiceCallsFinalizePendingRoute: typeof ApiPublicHooksVoiceCallsFinalizePendingRoute
  ApiPublicTwilioBiaDialRoute: typeof ApiPublicTwilioBiaDialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/voice-campaigns': {
      id: '/_authenticated/voice-campaigns'
      path: '/voice-campaigns'
      fullPath: '/voice-campaigns'
      preLoaderRoute: typeof AuthenticatedVoiceCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recuperacao': {
      id: '/_authenticated/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof AuthenticatedRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phone-numbers': {
      id: '/_authenticated/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/phone-numbers'
      preLoaderRoute: typeof AuthenticatedPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acordos': {
      id: '/_authenticated/acordos'
      path: '/acordos'
      fullPath: '/acordos'
      preLoaderRoute: typeof AuthenticatedAcordosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/twilio/bia-dial': {
      id: '/api/public/twilio/bia-dial'
      path: '/api/public/twilio/bia-dial'
      fullPath: '/api/public/twilio/bia-dial'
      preLoaderRoute: typeof ApiPublicTwilioBiaDialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/voice-calls-finalize-pending': {
      id: '/api/public/hooks/voice-calls-finalize-pending'
      path: '/api/public/hooks/voice-calls-finalize-pending'
      fullPath: '/api/public/hooks/voice-calls-finalize-pending'
      preLoaderRoute: typeof ApiPublicHooksVoiceCallsFinalizePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/debtors-auto-sync': {
      id: '/api/public/hooks/debtors-auto-sync'
      path: '/api/public/hooks/debtors-auto-sync'
      fullPath: '/api/public/hooks/debtors-auto-sync'
      preLoaderRoute: typeof ApiPublicHooksDebtorsAutoSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcordosRoute: typeof AuthenticatedAcordosRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPhoneNumbersRoute: typeof AuthenticatedPhoneNumbersRoute
  AuthenticatedRecuperacaoRoute: typeof AuthenticatedRecuperacaoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVoiceCampaignsRoute: typeof AuthenticatedVoiceCampaignsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcordosRoute: AuthenticatedAcordosRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPhoneNumbersRoute: AuthenticatedPhoneNumbersRoute,
  AuthenticatedRecuperacaoRoute: AuthenticatedRecuperacaoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVoiceCampaignsRoute: AuthenticatedVoiceCampaignsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksDebtorsAutoSyncRoute: ApiPublicHooksDebtorsAutoSyncRoute,
  ApiPublicHooksVoiceCallsFinalizePendingRoute:
    ApiPublicHooksVoiceCallsFinalizePendingRoute,
  ApiPublicTwilioBiaDialRoute: ApiPublicTwilioBiaDialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
